languageName = "English"
weight = 1
title = "Aspen's Blog"

[params]
  rtl = false
  dateFormat = "2 January 2024"
  #logo = "img/logo.png"
  #secondaryLogo = "img/logo.png"
  description = "My awesome blog"
  #copyright = "_Copy_ _right_ :thinking_face:"

[author]
   name = "太一"
   image = "img/author.jpeg"
   bio = ""
   links = [
     { email = "mailto:devaspenbranch@gmail.com" },
     { github = "https://github.com/aspenbranch" },
   ]
